################################################################################
########                                                                ########
########                Makefile generated by µMake                     ########
########                                                                ########
########                                 https://gitlab.com/Arc-Pintade ########
################################################################################

#          here, libraries have been install with their natural path           #
#  To keep this structure give the same name as your mains to your executables #
#                                                                              #
#                                    Library                                   #
#                                     SFML                                     #

#                                                                              #
#                                   Thesaurus                                  #
#                           $@ : name of file target                           #
#                         $< : name of first dependency                        #
#                         $^ : name of all dependencies                        #

######################## Compiler variable definitions #########################

CC     = gcc
CFLAGS = -std=c++17 -O3 -Wall -Wextra -Wpedantic 
LIBS   = -lm -lstdc++ 

######################## Directory variable definitions ########################

SOURCES_DIR  = src
SCRIPTS_DIR  = scripts
BUILDS_DIR   = build
BINARIES_DIR = bin

######################### Library variable definitions #########################

SFML_LIBS    = -lsfml-graphics -lsfml-window -lsfml-system
OPENGL_LIBS  = -lGL -lGLU -lGLEW -I./include

ALL_LIBS     = $(SFML_LIBS) $(OPENGL_LIBS)

########################## Intern variable definitions #########################

SOURCES      = $(shell ls ./$(SOURCES_DIR)/*.cpp)
SCRIPTS      = $(shell ls ./$(SCRIPTS_DIR)/*.cpp)
SOURCES_OBJ  = $(SOURCES:.cpp=.o)
SCRIPTS_OBJ  = $(SCRIPTS:.cpp=.o)
SCRIPTS_BIN  = $(SCRIPTS:.cpp=.x)

########################## Executable name definitions #########################

OBJECTS      = $(subst $(SOURCES_DIR),$(BUILDS_DIR),$(SOURCES_OBJ))
EXECUTABLE   = $(notdir $(SCRIPTS_BIN))

############################### Makefile commands ##############################

.PRECIOUS: $(BUILDS_DIR)/%.o
.PHONY: clean clean-all check
all: $(EXECUTABLE)
	@echo "\n"\
	"*********************************\n"\
	"**     Compilation done :)     **\n"\
	"*********************************\n"

clean:
	rm -f ./$(BUILDS_DIR)/*.o
clean-all:
	rm -f ./$(BUILDS_DIR)/*.o ./$(BINARIES_DIR)/*
check:
	@echo $(EXECUTABLE)

############################### Objects creations ##############################

$(BUILDS_DIR)/%.o: $(SCRIPTS_DIR)/%.cpp
	$(CC) $(CFLAGS) $(ALL_LIBS) -c $< -o $@


$(BUILDS_DIR)/%.o: $(SOURCES_DIR)/%.cpp
	$(CC) $(CFLAGS) $(ALL_LIBS) -c $< -o $@

############################# Executables creations ############################

%.x: $(BUILDS_DIR)/%.o $(OBJECTS)
	$(CC) $(CFLAGS) -o $(BINARIES_DIR)/$@ $^ $(LIBS) $(ALL_LIBS)

#################################### Bye :) ####################################
